title: Joint Polytechnic Academy for Educators JP-AcE
url: https://jpace.polytechnic.edu.sg
favicon: /images/web version updated on 7 sep 2022.png
colors:
  primary-color: "#006241"
  secondary-color: "#002a5f"
  media-colors:
    - title: media-color-one
      color: "#5a0611"
    - title: media-color-two
      color: "#530a61"
    - title: media-color-three
      color: "#157078"
    - title: media-color-four
      color: "#04a8b7"
    - title: media-color-five
      color: "#07306b"
description: >-
  The Joint Polytechnic Academy for Educators (JP-AcE) is a centralised academy
  for T&L capability development of educators in polytechnics and industry.


  It offers joint polytechnic suite of T&L baseline capability development programmes and certifications, such as the Certificate in T&L for Polytechnic Educators (CTLPE), School Leadership Move-In Programme (SLMP), T&L Mentor Move-In  Programme (TLMP), Course Leadership Move-In Programme (CLMP) and other programmes which strengthens the T&L capabilities of polytechnic educators. 


  In addition, it collaborates with Institute of Adult Learning (IAL) and partners to create and deliver programmes in area of adult education. 


  This is an Isomer site of the Singapore Government.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3r64eq67610w8.amplifyapp.com/
prod: https://master.d3r64eq67610w8.amplifyapp.com/
shareicon: /images/web version updated on 7 sep 2022.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: jp-ace-resource
